name: NetFrameWork.Legacy.CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore packages
      run: nuget restore DInvoke\DInvoke.sln
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Build with MSBuild
      run: msbuild  DInvoke\DInvoke.sln -p:Configuration=Release
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DInvoke AnyCPU Release
        path: DInvoke\DInvoke\bin\Release\DInvoke.dll
